import React from "react";
import { Link } from "react-router-dom";

//Mock logo generated by Dalle

function Navbar(props) {
    return (
            <div className="nav-area">
                <Link className="nav-icon-link" to="/">
                    <img className = "nav-icon" alt="Website icon" src={require("../logo.png")}/>
                </Link>

                {props.username !== null &&
                    <>
                        <b className="navbar-welcome">Welcome {props.username}</b>
                    </>
                }
                <div className="nav-buttons">                
                    <ul>
                        <li>
                            <Link className="nav-link" to="/">Home</Link>
                        </li>
                        <li>
                            <Link className="nav-link" to="/browse">Products</Link>
                        </li>
                        {props.username === null ?
                        <>
                            <li>
                                <Link className="nav-link" to="/login">Log In</Link>
                            </li>
                        </>
                        :
                        <>  
                            <li>
                                <Link className="nav-link" to="/cart">Shopping</Link>
                            </li>
                            <li>
                                <Link className="nav-link" to="/profile">Account</Link>
                            </li>
                            <li>
                                <Link className="nav-link" to="/login" onClick={props.logoutUser}>Log Out</Link>
                            </li>

                        </>
                        }
                    </ul>
                </div>
            </div>
    );
}

export default Navbar;
